"""refactor_workforce

Revision ID: 32917632ac02
Revises: 
Create Date: 2026-06-16 04:55:05.120734
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '32917632ac02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_labour_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=False),
    sa.Column('workers_count', sa.Integer(), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_labour_summary_id'), 'daily_labour_summary', ['id'], unique=False)
    op.drop_index('ix_attendance_id', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_workers_id', table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', 'HALF_DAY', 'OVERTIME', 'LEAVE', name='attendancestatus'), autoincrement=False, nullable=False),
    sa.Column('hours_worked', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overtime_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('marked_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name='attendance_marked_by_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='attendance_project_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name='attendance_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey')
    )
    op.create_index('ix_attendance_id', 'attendance', ['id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trade', postgresql.ENUM('MASON', 'CARPENTER', 'ELECTRICIAN', 'PLUMBER', 'PAINTER', 'HELPER', 'OTHER', name='tradetype'), autoincrement=False, nullable=False),
    sa.Column('daily_wage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('contractor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('join_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bank_account', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('aadhar_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name='workers_contractor_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='workers_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workers_pkey'),
    sa.UniqueConstraint('worker_id', name='workers_worker_id_key')
    )
    op.create_index('ix_workers_id', 'workers', ['id'], unique=False)
    op.drop_index(op.f('ix_daily_labour_summary_id'), table_name='daily_labour_summary')
    op.drop_table('daily_labour_summary')
    # ### end Alembic commands ###
