"""add paid_amount to cost_records

Revision ID: m1n2o3p4q5r6
Revises: b17c6f8caefa
Create Date: 2026-07-21 14:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'm1n2o3p4q5r6'
down_revision: Union[str, None] = 'b17c6f8caefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_records', sa.Column('paid_amount', sa.Float(), nullable=True))
    op.execute("UPDATE cost_records SET paid_amount = 0.0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_records', 'paid_amount')
    # ### end Alembic commands ###
